## Carregar csv

In [43]:
import os
import pandas as pd

In [79]:
df = pd.read_csv("produtos_realistas_sujos.csv")
df.head()

,Ref Produto,Product Name,Desc,Preço Base,Barcode,Stock,Family,SubFamily,Color,Email Fornecedor
0,P001,Parafuso M6,Parafuso galvanizado,0.25,5.601235e+12,500,Fixacao,Parafusos,NaN,compras@metal.pt
1,P002,Tinta Exterior Branco,Tinta para exterior,12.99,5.601235e+12,55,Tintas,Exterior,Branco,tintas@cor.pt
2,P003,Martelo Profissional,Martelo aço forjado,19.90,5.601235e+12,20,Ferramentas,Manuais,Vermelho,ferr@tools.pt
3,P004,Broca 6mm,Broca para metal,abc,5.601235e+12,75,Ferramentas,Brocas,NaN,suporte@tools.pt
4,P005,Anilha M6,Anilha aço zincado,0.05,5.601235e+12,1200,Fixacao,Anilhas,Cinza,stock@metal.pt

In [62]:
print("Total rows: ", df.shape[0], " Total columns: ", df.shape[1])
print("Duplicated:", df["Ref Produto"].duplicated().sum())
print("Missing:", df["Preço Base"].isna().sum())
print("Unique:", df["Ref Produto"].nunique())

Total rows:  50  Total columns:  10
Duplicated: 2
Missing: 0
Unique: 47

In [68]:
display(
    df["Stock"]
    .value_counts()
    .sort_index()
    .reset_index()
    .rename(columns={
        "index": "Stock",
        "Stock": "Count"
    })
)

df["Stock"] = (df["Stock"].astype(str).str.replace(" unidades", "", regex=False))

display(
    df["Stock"]
    .value_counts()
    .sort_index()
    .reset_index()
    .rename(columns={
        "index": "Stock",
        "Stock": "Count"
    })
)

          Count  count
0           -10      1
1            10      1
2           100      2
3           110      1
4            12      1
5           120      1
6          1200      1
7            15      1
8           150      2
9            18      1
10            2      2
11           20      3
12  20 unidades      1
13          250      2
14           26      1
15           30      1
16          300      3
17           33      1
18           35      1
19            4      1
20           40      1
21          400      2
22           45      1
23          450      1
24            5      1
25           50      1
26          500      1
27           55      1
28           60      2
29          600      1
30           70      2
31          700      1
32           75      2
33           80      2
34          850      1
35           90      1
36          900      1

   Count  count
0    -10      1
1     10      1
2    100      2
3    110      1
4     12      1
5    120      1
6   1200      1
7     15      1
8    150      2
9     18      1
10     2      2
11    20      4
12   250      2
13    26      1
14    30      1
15   300      3
16    33      1
17    35      1
18     4      1
19    40      1
20   400      2
21    45      1
22   450      1
23     5      1
24    50      1
25   500      1
26    55      1
27    60      2
28   600      1
29    70      2
30   700      1
31    75      2
32    80      2
33   850      1
34    90      1
35   900      1

In [80]:
print("Missing:", df["Ref Produto"].isna().sum())
print("Duplicated:", df["Ref Produto"].duplicated().sum())
print("Unique:", df["Ref Produto"].unique())

Missing: 1
Duplicated: 2
Unique: ['P001' 'P002' 'P003' 'P004' 'P005' 'P006' 'P007' 'P008' 'P009' 'P010'
 'P011' 'P012' 'P013' 'P014' 'P015' nan 'P017' 'P018' 'P019' 'P020' 'P021'
 'P022' 'P023' 'P024' 'P025' 'P026' 'P027' 'P028' 'P029' 'P030' 'P031'
 'P032' 'P033' 'P034' 'P035' 'P036' 'P037' 'P038' 'P039' 'P041' 'P042'
 'P043' 'P044' 'P045' 'P046' 'P047' 'P048' 'P049']

In [81]:
nan_index = df[df["Ref Produto"].isna()].index[0]

df.loc[nan_index, "Ref Produto"] = "P016"

In [96]:
print("Unique:", df["Ref Produto"].unique())

Unique: ['P001' 'P002' 'P003' 'P004' 'P005' 'P006' 'P007' 'P008' 'P009' 'P010'
 'P011' 'P012' 'P013' 'P014' 'P015' 'P016' 'P017' 'P018' 'P019' 'P020'
 'P021' 'P022' 'P023' 'P024' 'P025' 'P026' 'P027' 'P028' 'P029' 'P030'
 'P031' 'P032' 'P033' 'P034' 'P035' 'P036' 'P037' 'P038' 'P039' 'P041'
 'P042' 'P043' 'P044' 'P045' 'P046' 'P047' 'P048' 'P049']

In [86]:
print("Missing:", df["Family"].isna().sum())
print("Duplicated:", df["Family"].duplicated().sum())
print("Unique:", df["Family"].unique())

Missing: 0
Duplicated: 43
Unique: ['Fixacao' 'Tintas' 'Ferramentas' 'Equipamento' 'Iluminacao' 'Outros'
 'ferramentas']

In [87]:
df["Family"] = (df["Family"].astype(str).str.replace("ferramentas", "Ferramentas", regex=False))

In [88]:
print("Missing:", df["Family"].isna().sum())
print("Duplicated:", df["Family"].duplicated().sum())
print("Unique:", df["Family"].unique())

Missing: 0
Duplicated: 44
Unique: ['Fixacao' 'Tintas' 'Ferramentas' 'Equipamento' 'Iluminacao' 'Outros']

In [89]:
print("Missing:", df["SubFamily"].isna().sum())
print("Duplicated:", df["SubFamily"].duplicated().sum())
print("Unique:", df["SubFamily"].unique())

Missing: 0
Duplicated: 38
Unique: ['Parafusos' 'Exterior' 'Manuais' 'Brocas' 'Anilhas' 'Porcas' 'Escadas'
 'Lanternas' 'Interior' 'Protecao' 'Diversos' 'LED']

In [95]:
for familia, df_fam in df.groupby("Family"):

    print(f"\n{'='*50}")
    print(f"FAMÍLIA: {familia}")
    print(f"{'='*50}")

    for subfamilia, df_sub in df_fam.groupby("SubFamily"):

        print(f"\n  Subfamília: {subfamilia}")

        for _, row in df_sub.iterrows():
            print(
                f"    {row['Ref Produto']} | "
                f"{row['Product Name']} | "
                f"{row['Barcode']} | "
                f"{row['Color']}"
            )

==================================================
FAMÍLIA: Equipamento
==================================================

  Subfamília: Escadas
    P007 | Escada Alumínio | 5601234500007.0 | Prateado
    P022 | Escada Fibra | 5601234500022.0 | Amarelo
    P030 | Escada Dobrável | 5601234500030.0 | Prateado
    P042 | Escada Telescópica | 5601234500042.0 | nan

  Subfamília: Protecao
    P011 | Óculos Segurança | 5601234500011.0 | Transparente
    P013 | Luva Proteção | 5601234500013.0 | Preto
    P014 | Fita Isoladora | 5601234500014.0 | Preto
    P026 | Capacete Obra | 5601234500026.0 | Amarelo
    P035 | Luva Industrial | 5601234500035.0 | Preto
    P045 | Capacete Branco | 5601234500045.0 | Branco

==================================================
FAMÍLIA: Ferramentas
==================================================

  Subfamília: Brocas
    P004 | Broca 6mm | 5601234500004.0 | nan
    P020 | Broca 8mm | nan | nan
    P028 | Broca SDS 10mm | 5601234500028.0 | nan
    P038 | Broca Madeira 5mm | 5601234500038.0 | nan
    P044 | Broca 12mm | 5601234500005.0 | nan

  Subfamília: Manuais
    P003 | Martelo Profissional | 5601234500003.0 | Vermelho
    P012 | Chave Inglesa | 5601234500012.0 | nan
    P016 | Serra Manual | 5601234500016.0 | nan
    P036 | Martelo Borracha | 5601234500036.0 | Preto
    P037 | Fita Métrica | 5601234500037.0 | nan

==================================================
FAMÍLIA: Fixacao
==================================================

  Subfamília: Anilhas
    P005 | Anilha M6 | 5601234500005.0 | Cinza
    P025 | Anilha M8 | 5601234500025.0 | nan
    P033 | Anilha M10 | 5601234500033.0 | nan

  Subfamília: Parafusos
    P001 | Parafuso M6 | 5601234500001.0 | nan
    P010 | Parafuso M8 | 5601234500010.0 | Prata
    P017 | Parafuso M10 | 5601234500017.0 | nan
    P023 | Parafuso Madeira | 5601234500023.0 | nan
    P031 | Parafuso M12 | 5601234500031.0 | nan
    P046 | Parafuso Auto-Roscante | 5601234500046.0 | nan

  Subfamília: Porcas
    P006 | Porca M8 | 5601234500006.0 | Cinza
    P018 | Porca M10 | 5601234500018.0 | nan
    P039 | Porca M12 | 5601234500039.0 | nan

==================================================
FAMÍLIA: Iluminacao
==================================================

  Subfamília: LED
    P034 | Projetor LED | 5601234500034.0 | Branco
    P049 | Lâmpada LED | 5601234500049.0 | Branco

  Subfamília: Lanternas
    P008 | Lanterna LED | 5601234500008.0 | Preto
    P019 | Lanterna Industrial | 5601234500019.0 | Amarelo
    P027 | Lanterna Compacta | 5601234500027.0 | Preto
    P043 | Lanterna Camping | 5601234500043.0 | Verde

==================================================
FAMÍLIA: Outros
==================================================

  Subfamília: Diversos
    P024 | nan | 5601234500024.0 | Preto
    P048 |  Produto 48  | 5601234500048.0 | nan

==================================================
FAMÍLIA: Tintas
==================================================

  Subfamília: Exterior
    P002 | Tinta Exterior Branco | 5601234500002.0 | Branco
    P015 | Tinta Exterior Azul | 5601234500015.0 | Azul
    P029 | Tinta Exterior Verde | 5601234500029.0 | Verde
    P041 | Tinta Exterior Preto | 5601234500041.0 | Preto

  Subfamília: Interior
    P009 | Tinta Interior Bege | 5601234500009.0 | Bege
    P021 | Tinta Interior Branco | 5601234500021.0 | Branco
    P032 | Tinta Interior Cinza | 5601234500032.0 | Cinza
    P047 | Tinta Interior Azul | 5601234500047.0 | Azul

In [94]:
df = df.drop_duplicates(subset=["Product Name"], keep="first")

In [98]:
display(df)
df.info()

,Ref Produto,Product Name,Desc,Preço Base,Barcode,Stock,Family,SubFamily,Color,Email Fornecedor
0,P001,Parafuso M6,Parafuso galvanizado,0.25,5.601235e+12,500,Fixacao,Parafusos,NaN,compras@metal.pt
1,P002,Tinta Exterior Branco,Tinta para exterior,12.99,5.601235e+12,55,Tintas,Exterior,Branco,tintas@cor.pt
2,P003,Martelo Profissional,Martelo aço forjado,19.90,5.601235e+12,20,Ferramentas,Manuais,Vermelho,ferr@tools.pt
3,P004,Broca 6mm,Broca para metal,abc,5.601235e+12,75,Ferramentas,Brocas,NaN,suporte@tools.pt
4,P005,Anilha M6,Anilha aço zincado,0.05,5.601235e+12,1200,Fixacao,Anilhas,Cinza,stock@metal.pt
5,P006,Porca M8,Porca sextavada,0.08,5.601235e+12,900,Fixacao,Porcas,Cinza,vendas@metal.pt
6,P007,Escada Alumínio,Escada 6 degraus,89.99,5.601235e+12,5,Equipamento,Escadas,Prateado,equip@empresa.pt
7,P008,Lanterna LED,Lanterna recarregável,19.99,5.601235e+12,15,Iluminacao,Lanternas,Preto,mail.com
8,P009,Tinta Interior Bege,Tinta lavável,11.50,5.601235e+12,150,Tintas,Interior,Bege,tintas@cor.pt
9,P010,Parafuso M8,Parafuso galvanizado,0.35,5.601235e+12,400,Fixacao,Parafusos,Prata,fornecedor@metal.pt
10,P011,Óculos Segurança,Proteção ocular,8.90,5.601235e+12,35,Equipamento,Protecao,Transparente,seguranca@empresa.pt
11,P012,Chave Inglesa,Ajustável,15.75,5.601235e+12,20 unidades,Ferramentas,Manuais,NaN,ferr@tools.pt
12,P013,Luva Proteção,Luva anti-corte,4.50,5.601235e+12,70,Equipamento,Protecao,Preto,epi@empresa.pt
13,P014,Fita Isoladora,Fita elétrica,1.99,5.601235e+12,250,Equipamento,Protecao,Preto,stock@empresa.pt
14,P015,Tinta Exterior Azul,Tinta exterior premium,13.49,5.601235e+12,60,Tintas,Exterior,Azul,tintas@cor.pt
15,P016,Serra Manual,Serra de mão,22.50,5.601235e+12,18,Ferramentas,Manuais,NaN,ferr@tools.pt
16,P017,Parafuso M10,Parafuso inox,0.45,5.601235e+12,300,Fixacao,Parafusos,NaN,compras@metal.pt
17,P018,Porca M10,Porca inox,0.10,5.601235e+12,450,Fixacao,Porcas,NaN,compras@metal.pt
18,P019,Lanterna Industrial,Lanterna alta potência,34.99,5.601235e+12,12,Iluminacao,Lanternas,Amarelo,led@light.pt
19,P020,Broca 8mm,Broca para metal,4.20,NaN,75,Ferramentas,Brocas,NaN,suporte@tools.pt
20,P021,Tinta Interior Branco,Tinta premium,12.50,5.601235e+12,110,Tintas,Interior,Branco,tintas@cor.pt
21,P022,Escada Fibra,Escada profissional,125.00,5.601235e+12,2,Equipamento,Escadas,Amarelo,equip@empresa.pt
22,P023,Parafuso Madeira,Parafuso madeira,0.12,5.601235e+12,600,Fixacao,Parafusos,NaN,compras@metal.pt
23,P024,NaN,Produto sem nome,9.99,5.601235e+12,30,Outros,Diversos,Preto,contacto@empresa.pt
24,P025,Anilha M8,Anilha aço,0.07,5.601235e+12,850,Fixacao,Anilhas,NaN,stock@metal.pt
25,P026,Capacete Obra,Capacete proteção,12.40,5.601235e+12,20,Equipamento,Protecao,Amarelo,epi@empresa.pt
26,P027,Lanterna Compacta,Lanterna pequena,9.50,5.601235e+12,45,Iluminacao,Lanternas,Preto,led@light.pt
27,P028,Broca SDS 10mm,Broca betão,7.80,5.601235e+12,-10,Ferramentas,Brocas,NaN,tools@empresa.pt
28,P029,Tinta Exterior Verde,Tinta premium,14.30,5.601235e+12,70,Tintas,Exterior,Verde,tintas@cor.pt
29,P030,Escada Dobrável,Escada compacta,69.99,5.601235e+12,4,Equipamento,Escadas,Prateado,equip@empresa.pt
30,P031,Parafuso M12,Parafuso inox,0.55,5.601235e+12,250,Fixacao,Parafusos,NaN,compras@metal.pt
31,P032,Tinta Interior Cinza,Tinta lavável,"12,50",5.601235e+12,120,Tintas,Interior,Cinza,tintas@cor.pt
32,P033,Anilha M10,Anilha inox,0.09,5.601235e+12,400,Fixacao,Anilhas,NaN,stock@metal.pt
33,P034,Projetor LED,Projetor exterior,45.90,5.601235e+12,10,Iluminacao,LED,Branco,led@light.pt
34,P035,Luva Industrial,Luva resistente,5.90,5.601235e+12,80,Equipamento,Protecao,Preto,epi@empresa.pt
35,P036,Martelo Borracha,Martelo técnico,11.00,5.601235e+12,26,Ferramentas,Manuais,Preto,ferr@tools.pt
36,P037,Fita Métrica,5 metros,3.50,5.601235e+12,90,Ferramentas,Manuais,NaN,tools@empresa.pt
37,P038,Broca Madeira 5mm,Broca específica,2.20,5.601235e+12,150,Ferramentas,Brocas,NaN,tools@empresa.pt
38,P039,Porca M12,Porca inox,0.12,5.601235e+12,300,Fixacao,Porcas,NaN,compras@metal.pt
40,P041,Tinta Exterior Preto,Tinta premium,14.90,5.601235e+12,50,Tintas,Exterior,Preto,tintas@cor.pt
41,P042,Escada Telescópica,Escada ajustável,149.90,5.601235e+12,2,Equipamento,Escadas,NaN,equip@empresa.pt
42,P043,Lanterna Camping,Lanterna portátil,17.50,5.601235e+12,33,Iluminacao,Lanternas,Verde,led@light.pt
43,P044,Broca 12mm,Broca para metal,5.80,5.601235e+12,80,Ferramentas,Brocas,NaN,tools@empresa.pt
44,P045,Capacete Branco,Capacete obra,11.90,5.601235e+12,60,Equipamento,Protecao,Branco,epi@empresa.pt
45,P046,Parafuso Auto-Roscante,Auto-roscante,0.18,5.601235e+12,700,Fixacao,Parafusos,NaN,compras@metal.pt
46,P047,Tinta Interior Azul,Tinta lavável,12.90,5.601235e+12,100,Tintas,Interior,Azul,tintas@cor.pt
47,P048,Produto 48,Com espaços extra,9.90,5.601235e+12,40,Outros,Diversos,NaN,contacto@empresa.pt
48,P049,Lâmpada LED,Lâmpada económica,3.50,5.601235e+12,300,Iluminacao,LED,Branco,led@light.pt

<class 'pandas.core.frame.DataFrame'>
Index: 48 entries, 0 to 48
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Ref Produto       48 non-null     object
 1   Product Name      47 non-null     object
 2   Desc              48 non-null     object
 3   Preço Base        48 non-null     object
 4   Barcode           47 non-null     float64
 5   Stock             48 non-null     object
 6   Family            48 non-null     object
 7   SubFamily         48 non-null     object
 8   Color             29 non-null     object
 9   Email Fornecedor  48 non-null     object
dtypes: float64(1), object(9)
memory usage: 4.1+ KB